/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { LanguageCode } from "./types/language";
export { LanguageCode } from "./types/language";
export namespace Components {
    interface AppHistory {
        /**
          * @default 'lb'
         */
        "language": LanguageCode;
    }
    interface AppHome {
        /**
          * @default 'lb'
         */
        "language": LanguageCode;
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppHistoryElement extends Components.AppHistory, HTMLStencilElement {
    }
    var HTMLAppHistoryElement: {
        prototype: HTMLAppHistoryElement;
        new (): HTMLAppHistoryElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-history": HTMLAppHistoryElement;
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppHistory {
        /**
          * @default 'lb'
         */
        "language"?: LanguageCode;
    }
    interface AppHome {
        /**
          * @default 'lb'
         */
        "language"?: LanguageCode;
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-history": AppHistory;
        "app-home": AppHome;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-history": LocalJSX.AppHistory & JSXBase.HTMLAttributes<HTMLAppHistoryElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
